// AUTO-GENERATED by informer-reports `publish-docs`. Do not edit.
// Import once from sidebars.js: const reportLibrarySidebar = require("./reportLibrarySidebar.js");
module.exports = {
  type: "category",
  label: "Report Library",
  items: [
    "report-library/index",
    {
      "type": "category",
      "label": "AR and GL",
      "items": [
        "report-library/naviga-coa-calculation",
        "report-library/naviga-invoices-with-payments",
        "report-library/naviga-simple-aging-summary"
      ]
    },
    {
      "type": "category",
      "label": "Campaigns",
      "items": [
        "report-library/naviga-ad-internet-orders-actual-gl-split",
        "report-library/naviga-ad-internet-orders-starter",
        "report-library/naviga-ad-internet-orders-starter-w-gl-revenue"
      ]
    },
    {
      "type": "category",
      "label": "Clients",
      "items": [
        "report-library/join-ad-brand-product-groups",
        "report-library/join-ad-brand-product-reps",
        "report-library/join-default-brand-rep",
        "report-library/naviga-client-brand-reps",
        "report-library/naviga-gen-clients"
      ]
    },
    {
      "type": "category",
      "label": "Informer Metadata",
      "items": [
        "report-library/metadata-dataset-dependencies",
        "report-library/metadata-reports-dataset-ids-names"
      ]
    }
  ]
};
