// AUTO-GENERATED by informer-reports `publish-docs`. Do not edit.
// Import once from sidebars.js: const reportLibrarySidebar = require("./reportLibrarySidebar.js");
module.exports = {
  type: "category",
  label: "Report Library",
  items: [
    "report-library/index",
    {
      "type": "category",
      "label": "Clients",
      "items": [
        "report-library/join-ad-brand-product-groups",
        "report-library/join-default-brand-rep"
      ]
    }
  ]
};
