/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  circSidebar: [
    {
      type: "category",
      label: "Circ Informer Dev",
      items: ["circ/circ-implementation"],
    },
  ],
  tutorialSidebar: [
    {
      type: "category",
      label: "Informer",
      items: [
        "informer/informer-new-ui",
        "informer/informer-video-training",
        "informer/informer-basics",
        "informer/informer-visuals",
        "informer/informer-sample-reports",
        "informer/informer-lookup-generator",
        "informer/informer-templates",
        "informer/informer-system",
      ],
    },
    {
      type: "category",
      label: "Informer Mappings",
      items: [
        "informer/informer-mappings-ad-internet-campaigns",
        "informer/informer-mappings-ad-internet-orders",
        "informer/informer-mappings-ar-invoices",
        "informer/informer-mappings-gen-clients",
        "informer/informer-mappings-ad-brands",
        "informer/informer-mappings-ad-publications",
        "informer/informer-mappings-cm-opportunities",
        "informer/informer-mappings-udf-fields",
        "informer/informer-mappings-ratecards",
        "informer/informer-mappings-other",
        "informer/informer-mappings-user-reports",
      ],
    },
    {
      type: "category",
      label: "Informer JavaScript",
      items: ["informer/informer-javascript", "informer/informer-saved-functions"],
    },
    {
      type: "category",
      label: "Informer API",
      items: ["informer/informer-rest-api", "informer/informer-rest-api-builder"],
    },
  ],
};
